--- 
javascripts: 
- base: 
  - prototype
  - rails
  - effects
  - controls
  - application
  - dragdrop
stylesheets: 
- base: 
  - blueprint/screen
  - custom
- print:
  - blueprint/print
- ie:
  - blueprint/ie

